#!/usr/bin/env php
<?php declare(strict_types=1);

if (version_compare('7.4.0', PHP_VERSION, '>')) {
    fwrite(
        STDERR,
        sprintf(
            'This version of AwesomeCli requires PHP >= 7.4.' . PHP_EOL .
            'You are using PHP %s (%s).' . PHP_EOL,
            PHP_VERSION,
            PHP_BINARY
        )
    );

    die(1);
}

if (!ini_get('date.timezone')) {
    ini_set('date.timezone', 'UTC');
}

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('PHP_COMPOSER_INSTALL', $file);

        break;
    }
}

unset($file);

if (!defined('PHP_COMPOSER_INSTALL')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
        '    composer install' . PHP_EOL . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );

    die(1);
}

require PHP_COMPOSER_INSTALL;

use AwesomePackages\AwesomeCli\Enum\Colors;
use AwesomePackages\AwesomeCli\Tools\Printer;

foreach ([__DIR__ . '/../../../src/config/commands.php', __DIR__ . '/src/config/commands.php'] as $file) {
    if (file_exists($file)) {
        define('REGISTERED_COMMANDS', $file);

        break;
    }
}

unset($file);

try {
    require REGISTERED_COMMANDS;
    $printer = new Printer();

    $printer->addMessage(AwesomePackages\AwesomeCli\CommandRunner::runCommand($argv[1] ?? null));
    $printer->send();
} catch (\Exception $exception) {
    $printer = new Printer();

    $printer->addMessage($exception->getMessage(), Colors::RED);
    $printer->send();
}
